"""users and tokens table

Revision ID: 8bab21336904
Revises:
Create Date: 2021-05-24 22:16:34.520425

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8bab21336904"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=70), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("avatar_url", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "oauth2token",
        sa.Column("name", sa.String(length=30), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("access_token", sa.String(length=200), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("token_type", sa.String(length=20), nullable=True),
        sa.Column("scope", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("access_token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oauth2token")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
